### ISSUE TITLE
Users can view a tour page for more detailed information about a tour

### ISSUE THREAD

**Issue by AlexMerchant** [Eva-Gaivoronski/altas#13]
**STORY:** As any user, I would like to be able to view a summary of the tour and the full tour itinerary before beginning the tour, so I can get an idea of what the overall tour holds.

**DONE:** A summary map holding markers of all Stops defined in the itinerary is given at the top of the page. Further below, a list of all stops in a tour are returned in an itinerary table with their own map snippets and marker, name of the stop, the address, a description, estimated tour length, a rating score, and reviews.

**Comment by lhedrick05** [comment]
Done for basic functionality
