### ISSUE TITLE
Project Planning - UML & Wireframe

### ISSUE THREAD

**Issue by Cresence** [Eva-Gaivoronski/altas#3]
See our Figma link for the [wireframe](https://www.figma.com/file/W6aXAVIqCmnVdaA95ZebOq/Get-Cultured-Web-App?type=whiteboard&node-id=0-1&t=CbjrhbUd7mPhCAfP-0):

https://www.figma.com/file/W6aXAVIqCmnVdaA95ZebOq/Get-Cultured-Web-App?type=whiteboard&node-id=0-1&t=CbjrhbUd7mPhCAfP-0

**Comment by lhedrick05** [comment]
Figma link reflects the design of model classes as well as relationship structure.
